### ISSUE TITLE
Multiple DNS Zones

### ISSUE THREAD

**Issue by theonethread** [dschoeffm/hetzner-dns-certbot#9]
Hey,
I mentioned you in my [community article](https://community.hetzner.com/tutorials/secure-fedora-webserver#step-8---setup-certificate-auto-renewal), and now I am in need for some fine tuning.
With my current setup I am in the need to support multiple DNS zones, meaning multiple tokens - this could be a cli arg for your script with backward compatibility. If you're open to such contribution, I'd rather dust off my shell knowledge and make a PR, than fork your work, what do you think?
Barnabas

**Comment by dschoeffm** [comment]
Hi Barnabas,
I'm currently not actively using (and therefore maintaining) these scripts. I do appreciate you asking, but I think it might be better if you were to fork the repo. Since I am not using the DNS service anymore I don't really have a method of testing changes, and doing my due diligence on changes commited to this repos.
If you do decide to to fork it, feel free to tell me, and I will probably set a link in the Readme.
Dominik

**Comment by theonethread** [comment]
Hi Dominik,
Thanks for the reply and support, I will let you know, if I publish anything publicly based on your work - though might take a while, currently do not really have time to polish-up my POC side-projects.
